### ISSUE TITLE
pct_safn

### ISSUE THREAD

**Issue by juliaabond** [jasonelaw/nrsa#15]
**pct_safn (Substrate Percent Sand and Fines -- <2 mm)**
The pct_safn value is not always equal to the sum of pct_fn and pct_sa (total_fines column in the table below). Perhaps a rounding issue? I'm guessing that the pct_safn value is actually correct (but maybe there is the same integer issue) and it is the pct_fn and pct_sa values that have been rounded when stored as integers.

![image](https://user-images.githubusercontent.com/25557467/43667820-877a9f72-972e-11e8-90e7-1154223ef5d7.png)

**Comment by jasonelaw** [comment]
All rounding issues are database issues. We can try to loop Steve into the conversation, but I don't know how they want database issues reported. Honestly, I'm not sure why we are rounding proportions to whole numbers. It seems a little draconian.

**Comment by juliaabond** [comment]
Addressed. #
