### ISSUE TITLE
Add pct_bdrk metric

### ISSUE THREAD

**Issue by juliaabond** [jasonelaw/nrsa#17]
I believe we missed the **pct_bdrk** metric (percent bedrock) in our original list of metrics. It needs to be added.

When summing all of the substrate percents, very few of the totals equal 100%. For some of the sample events, I believe this is a result of the missing bedrock percents (pct_bdrk). For others, this may be related to my question with issue #16.

![image](https://user-images.githubusercontent.com/25557467/43669371-3bcf643c-9737-11e8-8ee3-96c566849291.png)

**Comment by jasonelaw** [comment]
Some of the metrics are [sums of groups of categories](https://github.com/jasonelaw/nrsa/blob/e287cc9fb3acab784c513bddb6cd0d440b6d7b1d/R/calculateSubstrateMetrics.r#L161-L166). The original categories should be pct_om, pct_ot, pct_wd, pct_hp, pct_fn, pct_sa, pct_gf, pct_gc, pct_cb, pct_sb, pct_xb, pct_bl, pct_rs, pct_rr, and pct_rc. You can safely drop pct_om (see #18 ). These should sum to 100. Adding in composite metrics like pct_bdrk will get you sums > 100.
