### ISSUE TITLE
d50 - NA values

### ISSUE THREAD

**Issue by juliaabond** [jasonelaw/nrsa#19]
**d50 (Median mobile substrate diameter)**
There are approx. 40 records in the DB with d50 values of _NA_. All of these have very high values for percent fines (pct_fn), but that may not have anything to do with it.
 

![image](https://user-images.githubusercontent.com/25557467/43670134-8d8030a8-973d-11e8-8fc5-b0c8696bfc46.png)

**Comment by jasonelaw** [comment]
These aren't calculated for boatable sites.
