### ISSUE TITLE
d50 - change DB data type

### ISSUE THREAD

**Issue by juliaabond** [jasonelaw/nrsa#20]
**d50 (Median mobile substrate diameter)**
Approx. 50 of the records have a D50 value of 0. I'm guess this is because the pct_fn substrate size corresponds to 0.001 and the pct_sa substrate size corresponds to 0.06mm, so the small value is being rounded to zero when converting to an integer.

To resolve this we need to modify the data type in the DB.

![image](https://user-images.githubusercontent.com/25557467/43670205-15227052-973e-11e8-994b-ec921e626d8c.png)

**Comment by jasonelaw** [comment]
I think this has been fixed in db.
