### ISSUE TITLE
site_identifier - remove trailing whitespace

### ISSUE THREAD

**Issue by juliaabond** [jasonelaw/nrsa#22]
There is either a tab or 5 spaces at the end of each 'site_identifier' value in the DB.

**Comment by jasonelaw** [comment]
I can guarantee that this is because it's a fixed length field. We're going
to have to try to separate calculation issues from database issues. All
rounding, data type issues are database issues. Of course if you're unsure,
log it.

**Comment by juliaabond** [comment]
Fixed.
