### ISSUE TITLE
medbkun all 0's

### ISSUE THREAD

**Issue by PDXChris** [jasonelaw/nrsa#24]
medbkun is all 0's or NA's, which may be appropriate but I know of at least one site in Balch Creek along Cornell Rd. that has nice undercut bank.

**Comment by jasonelaw** [comment]
In all of the data collected so far, here's the breakdown of undercut banks > 0:
```r
> table(raw$bank$undercut > 0, useNA = 'ifany')

FALSE  TRUE  <NA> 
 4554   106    40 
```
Sooooo, the median is extraordinarily unlikely to be anything other than 0.
